### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zavalacl/proj10#1]
It looks like I'm getting [an error on Heroku](https://immense-tor-6070.herokuapp.com/musics). Did you forget to migrate the database on Heroku?

**Comment by zavalacl** [comment]
Hi, I updated this project and uploaded the next project (wk12) as well! Can you take a look at them? Thanks! :)

**Comment by chrisvfritz** [comment]
It looks like you have [some styling here](https://github.com/zavalacl/proj10/blob/master/app/assets/stylesheets/static.css#L1-L3) that's affecting the form errors, making them show up next to each other instead of in a list. Can you fix this so that this style only affects the navbar, as it's probably intended?

**Comment by zavalacl** [comment]
Hey I updated proj10! Take a look please! :)

**Comment by chrisvfritz** [comment]
:+1: Looks good!
